### PR TITLE
Update PULL_REQEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by skanda890**
- [X] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#coding), and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**.
- [X] **Have you checked that there aren't other open [pull requests](https://github.com/marticliment/WingetUI/pulls) for the same changes?**
- [X] **Have you tested that the committed code can be executed without errors?**
- [X] **This PR is not composed of garbage changes used to farm GitHub activity to enter potential Crypto AirDrops.**
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the contributors' time, who have to spend their free time reviewing, fixing, and testing code that does not even compile breaks other features, or does not introduce any useful changes. Thank you for your understanding.
-----
Change the text provided by the user in the "optionally, explain here about the committed code" sentence font size from heading to normal.

-----

Closes #XXXX

Relates to #XXXX

### CODE REVIEW

**Comment by marticliment** [comment]
But you are editing a comment. I have tested the changes and they change nothing

**Comment by marticliment** [comment]
Also, Why is there so many commit history?

**Comment by skanda890** [comment]
> But you are editing a comment. I have tested the changes and they change nothing

I meant in PULL_REQUEST_TEMPLATE.md

**Comment by skanda890** [comment]
> Also, Why is there so much commit history?

Since I reverted a PR, actually I don't know.

**Comment by skanda890** [comment]
> > Also, Why is there so much commit history?
> 
> Since I reverted a PR, actually I don't know.

I will try to change that.

**Comment by marticliment** [comment]
Please open a new PR with the changes

**Comment by skanda890** [comment]
PR moved from #2605 to #2607.

**Pull request closed without merging**
