### PR TITLE
Create .deepsource.toml, .whitesource, and Update WebBasedData/test_urls.py

### PR DESCRIPTION
**Pull request by skanda890**
- [X] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#coding), and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**.
- [X] **Have you checked that there aren't other open [pull requests](https://github.com/marticliment/WingetUI/pulls) for the same changes?**
- [X] **Have you tested that the committed code can be executed without errors?**
- [X] **This PR is not composed of garbage changes used to farm GitHub activity to enter potential Crypto AirDrops.**
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the contributors' time, who have to spend their free time reviewing, fixing, and testing code that does not even compile breaks other features, or does not introduce any useful changes. Thank you for your understanding.
-----
Create .deepsource.toml and .whitesource to check for security issues and more.

-----

### CODE REVIEW

**Comment by skanda890** [comment]
@marticliment, please review this and give some suggestions.

**Comment by marticliment** [comment]
please do not autoformat code

**Comment by skanda890** [comment]
> please do not autoformat code

Reverted!

**Comment by skanda890** [comment]
> Please do not autoformat code

Reverted! @marticliment, any more suggestions?

**Comment by marticliment** [comment]
Why the refractoring?

**Comment by marticliment** [comment]
What do this files ( .deepsource.toml, .whitesource) do?

**Comment by skanda890** [comment]
> Why the refractoring?

To check if a variable is equal to one of many values, combine the values into a tuple and check if the variable is contained `in` it instead of checking for equality against each of the values. This is faster, less verbose, and more readable.

**Comment by skanda890** [comment]
> What do this files ( .deepsource.toml, .whitesource) do?

These files configure security bots like MendBolt and DeepSource.

**Comment by skanda890** [comment]
@marticliment, please accept or deny this as soon as possible as I am deleting all my forked repositories.

**Comment by marticliment** [comment]
Give me one week

**Review by marticliment — APPROVED** [review]

**Pull request merged**
