### PR TITLE
#2605

### PR DESCRIPTION
**Pull request by skanda890**
- [ ] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#coding), and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**.
- [ ] **Have you checked that there aren't other open [pull requests](https://github.com/marticliment/WingetUI/pulls) for the same changes?**
- [ ] **Have you tested that the committed code can be executed without errors?**
- [ ] **This PR is not composed of garbage changes used to farm GitHub activity to enter potential Crypto AirDrops.**
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the contributors' time, who have to spend their free time reviewing, fixing, and testing code that does not even compile breaks other features, or does not introduce any useful changes. Thank you for your understanding.
-----
#2605

-----

### CODE REVIEW

**Comment by Lockszmith-GH** [comment]
image

You need to take care of your repo first.

**Comment by marticliment** [comment]
@skanda890, the pr still has the commit history here. I will make the changes manually.

**Comment by skanda890** [comment]
Can you send the PR where you are going to make the changes.

**Comment by Lockszmith-GH** [comment]
@skanda890 

Below are 2 SO Q&A about your predicement, hope you find it helpful.

https://stackoverflow.com/questions/41283955/github-keeps-saying-this-branch-is-x-commits-ahead-y-commits-behind
https://stackoverflow.com/questions/29049650/github-fork-your-branch-is-5-commits-ahead-how-to-clean-this-without-pushing

**Pull request closed without merging**
