### PR TITLE
Fix csproj duplicates and warnings

### PR DESCRIPTION
**Pull request by Saibamen**
Fix some of csproj duplicated entries.
Fix some of warnings

### CODE REVIEW

**Review by marticliment — DISMISSED** [review]

**Comment by marticliment** [comment]
Aside from passigng the tests, have you tested that UniGetUI still works?

**Comment by marticliment** [comment]
Edit, it is not passing tests

**Comment by Saibamen** [comment]
>Aside from passigng the tests, have you tested that UniGetUI still works?

No, because I'm still having build error in my Visual Studio:
image

This is why I added https://github.com/marticliment/UniGetUI/pull/3057

What should I install in my VS?

**Comment by marticliment** [comment]
You need to install the Windows App Sdk version 10.0.26100.0 or 10.0.19041.0 (i am sorry, I can't recall which)

**Comment by Saibamen** [comment]
image

`10.0.26100.0` is for Win 11, `10.0.19041.0` is for Win 10.

I will install `19041`. It is strange that Visual Studio can't suggest installing missing components via Visual Studio Installer (he did that for other components, for example .NET SDK)

**Comment by Saibamen** [comment]
It works

image

**Review by marticliment — APPROVED** [review]

**Pull request merged**
