### PR TITLE
Update Pull Request Template.md

### PR DESCRIPTION
**Pull request by skanda890**
- [X] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#coding), and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**.
- [X] **Have you checked that there aren't other open [pull requests](https://github.com/marticliment/WingetUI/pulls) for the same changes?**
- [X] **Have you tested that the committed code can be executed without errors?**
- [X] **This PR is not composed of garbage changes used to farm GitHub activity to enter potential Crypto AirDrops.**
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the contributors' time, who have to spend their free time reviewing, fixing, and testing code that does not even compile, breaks other features or does not introduce any useful changes. Thank you for your understanding.

-----

Update Pull Request Template.md
-----

### CODE REVIEW

**Comment by marticliment** [comment]
What does this PR do?

Please explain

**Comment by skanda890** [comment]
> What does this PR do?
> 
> Please explain

This merges multiple branches, of marticliment/UniGetUI, and update .md files.

**Comment by marticliment** [comment]
No, these branches are not ready yet, please do not publish PRs for branches that already have their own PR/Draft PR

**Comment by skanda890** [comment]
I will make changes and be back.

**Comment by skanda890** [comment]
Changes done in #2493

**Pull request closed without merging**
