### PR TITLE
Update icons and screenshots from the excel file

### PR DESCRIPTION
**Pull request by skanda890**
- [X] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#coding), and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**.
- [X] **Have you checked that there aren't other open [pull requests](https://github.com/marticliment/WingetUI/pulls) for the same changes?**
- [X] **Have you tested that the committed code can be executed without errors?**
- [X] **This PR is not composed of garbage changes used to farm GitHub activity to enter potential Crypto AirDrops.**
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the contributors' time, who have to spend their free time reviewing, fixing, and testing code that does not even compile breaks other features, or does not introduce any useful changes. Thank you for your understanding.

-----
https://github.com/marticliment/UniGetUI/pull/2353/commits/979244590bba9642508be83522339d8f39a7bea5

---

### CODE REVIEW

**Comment by marticliment** [comment]
but this changes nothing?

**Comment by marticliment** [comment]
Why?

**Comment by skanda890** [comment]
> Why?

Since it is the same.

**Comment by marticliment** [comment]
I don't want to confuse git too much as I have already had bad experiences with merging nonchanged PRs

**Pull request closed without merging**
