### PR TITLE
Better keyboard navigation

### PR DESCRIPTION
**Pull request by mrixner**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#coding), and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**.
- [x] **Have you checked that there aren't other open [pull requests](https://github.com/marticliment/WingetUI/pulls) for the same changes?**
- [x] **Have you tested that the committed code can be executed without errors?**
- [x] **This PR is not composed of garbage changes used to farm GitHub activity to enter potential Crypto AirDrops.**
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the contributors' time, who have to spend their free time reviewing, fixing, and testing code that does not even compile breaks other features, or does not introduce any useful changes. I appreciate your understanding.
-----

This pull request allows typing in a package list view to jump to that package, much like how Windows Explorer allows you to type out a file name on your keyboard outside of the search bar to jump directly to the file.

I tried to solve #1217 but I couldn't get `SelectedIndex` and such to work, so I ended up using `FilteredPackage.IndexOf(PackageList.SelectedItem)` and then after all of that apparently the `Select` call doesn't _actually_ select the element and pressing enter would open the package details for the previously selected element, which I don't know how to fix (or even what the problem is). It occurs to me that this affects this code as well, but the main purpose is to focus the element on the screen.

### CODE REVIEW

**Comment by marticliment** [comment]
> I tried to solve #1217 but I couldn't get `SelectedIndex` and such to work, so I ended up using `FilteredPackage.IndexOf(PackageList.SelectedItem)`

You can fix this by using the `Index` property of the `PackageWrapper` items that come from the `ObservablePackageCollection` structure (`AbstractPackagesPage.FilteredPackages`), instead of finding the package on the list (with still would work but wouldn't be as efficient.)


I think #1217 is more of a limitation with how ItemsView handles item focus by default. In fact, after pressing a package on the list arrow navigation works.

Perhaps I could implement arrow press detection, and if the user presses an arrow key and no item is selected the first/last item could be manually selected and then focus given to the package list, so it feels more like the Windows explorer. If you want, I can do this.

**Comment by mrixner** [comment]
> You can fix this by using the Index property of the PackageWrapper items that come from the ObservablePackageCollection structure (AbstractPackagesPage.chat), instead of finding the package on the list (with still would work but wouldn't be as efficient.)

Ahh, OK. Done, thanks.

> I think https://github.com/marticliment/UniGetUI/issues/1217 is more of a limitation with how ItemsView handles item focus by default. In fact, after pressing a package on the list arrow navigation works.

Yeah, I noticed this. #1217 was, I think, primarily about making it loop back around, but I've also noticed that occasionally using the arrow keys moves the ListView, not the focused element.

> Perhaps I could implement arrow press detection, and if the user presses an arrow key and no item is selected the first/last item could be manually selected and then focus given to the package list, so it feels more like the Windows explorer. If you want, I can do this.

Yeah, this isn't that hard; fixed in 1d1ee33.

I think the two solutions to making the keyboard navigation actually useful is that `SelectAndScrollTo` needs to put the focus on the selected element, which I couldn't figure out how to do, or `PackageItemContainer_KeyUp` ([AbstractPackagesPage.xaml.cs:907](https://github.com/mrixner/UniGetUI/blob/fee02f95a450ac16b5eec36398afc5db84a560f9/src/UniGetUI/Pages/SoftwarePages/AbstractPackagesPage.xaml.cs#L909)) needs to use the `SelectedItem` instead of the `sender`.

**Comment by marticliment** [comment]
> I think the two solutions to making the keyboard navigation actually useful is that `SelectAndScrollTo` needs to put the focus on the selected element, which I couldn't figure out how to do, or `PackageItemContainer_KeyUp` ([AbstractPackagesPage.xaml.cs:907](https://github.com/mrixner/UniGetUI/blob/fee02f95a450ac16b5eec36398afc5db84a560f9/src/UniGetUI/Pages/SoftwarePages/AbstractPackagesPage.xaml.cs#L909)) needs to use the `SelectedItem` instead of the `sender`.

I don't think the second is possible, do you think that forcing focus on the ItemsView on SelectAnScrollTo could fix the issue?

**Comment by mrixner** [comment]
> I don't think the second is possible, do you think that forcing focus on the ItemsView on SelectAnScrollTo could fix the issue?

Yeah, I'm pretty sure the problem is that while the item is selected, the focused item doesn't change, and the focused item is the one sending the event.

**Comment by mrixner** [comment]
Correction: forcing focus on the _ItemView_ wouldn't work, the focus has to be on the element being selected.

**Comment by marticliment** [comment]
I am then afraid that this issue cannot be fixed by a limitation on WinUI

**Comment by mrixner** [comment]
Ahh, that's unfortunate. I would've really appreciated this :( I suppose I should remove the arrow key code then, since it doesn't make much sense to a) hinder the default behavior and b) have arrow key selection that doesn't actually allow enter-for-package details. Is my assessment correct?

**Comment by mrixner** [comment]
> I don't think the second is possible

Could I ask why not? Does the Sender expose something `SelectedItem` doesn't? Or is it better practice?

**Comment by marticliment** [comment]
> Could I ask why not? Does the Sender expose something `SelectedItem` doesn't? Or is it better practice

Tested it twice and didn't succeed. They seem to be unreliable. Or at least when I tried I couldn't get them to work.

**Comment by marticliment** [comment]
I have been testing the code, and I have observed the following behaviour:
Pressing multiple times the same key does not iterate over packages starting with the same key (it should do that if the goal is to mimic windows explorer). Instead, it jumps to a random package. Let me give details:
 1. Press letter `b`. Package _BDlot DVD master_ gets highlighted (as expected).
 2. Press letter `b` (again). Instead of _Beaker_ being selected, _Anki_ gets selected, which is not even the first package that starts with letter a.
 3. Pressing the letter `b` more times will remain on _Anki_ being selected.

**Review by marticliment — CHANGES_REQUESTED** [review]
Issue mentioned on the PR conversation

**Comment by mrixner** [comment]
Anki is probably being selected because it's ID has a `bb` in it? I noticed this in explorer the other day but I didn't even know that was the functionality before lol... I'll go fix it.

**Comment by marticliment** [comment]
> Anki is probably being selected because it's ID has a `bb` in it?

No, it's id is `Anki.Anki`

**Comment by mrixner** [comment]
Well that's really bizarre then, I can't imagine why that would be.

**Comment by marticliment** [comment]
Please mark the conversation as resolved when you can fix the issue, thanks!

**Review by mrixner — COMMENTED** [review]
Fixes implemented

**Comment by mrixner** [comment]
> Please mark the conversation as resolved when you can fix the issue, thanks!

Uhh... I'm not sure how...

**Review by marticliment — APPROVED** [review]

**Pull request merged**
