### PR TITLE
Add a "Cancel All Operations" Button

### LINKED ISSUE #1474: [ENHANCEMENT] Provide a method for bulk cancelling all remaining updates
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

I just downloaded and started using WingetUI for the first time. I was shown that I had 40+ available updates and selected the `#` symbol which began updating all packages. I selected this because I was not aware of what it did which looks like that issue is going to be addressed in #1410. Anyways, I wanted to cancel all the in-progress updates so that I could update packages using the interactive method instead, but it only gave me the option to cancel individual updates. I think it would be nice to have a button or option that let you cancel all in progress updates instead so that a user could change their mind and avoid having to close out of the program and reopen.

### Describe how this improvement could help users.

Users could cancel all in progress updates at once rather than cancelling them 1 by 1 which is inconvenient for a large number of updates.

### PR DESCRIPTION
**Pull request by mrixner**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#coding), and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**.
- [x] **Have you checked that there aren't other open [pull requests](https://github.com/marticliment/WingetUI/pulls) for the same changes?**
- [x] **Have you tested that the committed code can be executed without errors?**
- [x] **This PR is not composed of garbage changes used to farm GitHub activity to enter potential Crypto AirDrops.**
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the contributors' time, who have to spend their free time reviewing, fixing, and testing code that does not even compile breaks other features, or does not introduce any useful changes. I appreciate your understanding.
-----

As the title says; adds a button to the updates page toolbar to cancel all operations.

-----

Closes #1474

### CODE REVIEW

**Comment by marticliment** [comment]
> As the title says; adds a button to the updates page toolbar to cancel all operations.

Is this button added only to the updates page? I reckon it would make sense to add it on the 4 toolbars... Or perhaps it could be added to the "More" flyout menu, right above the "Quit UniGetUI button":
image

**Comment by mrixner** [comment]
> > As the title says; adds a button to the updates page toolbar to cancel all operations.
> 
> Is this button added only to the updates page? I reckon it would make sense to add it on the 4 toolbars... Or perhaps it could be added to the "More" flyout menu, right above the "Quit UniGetUI button":
> image
> 

Yeah, it's only on the update page. Adding it to the menu flyout instead is a good idea but most people who need it will never find it, at least in time to cancel the operations they messed up. Do you think it makes more sense in the flyout or on each page? Or maybe add it to the little queue list thingy at the bottom?

**Comment by marticliment** [comment]
> Do you think it makes more sense in the flyout or on each page? Or maybe add it to the little queue list thingy at the bottom?

Not gonna lie, the entire operations list is lacking some features (resizable operation space, as in 2.x.x, collapse/expand list button, etc.) which I plan to add when I make the operation rewrite (I will change both backend and UI for operations), so perhaps the button can go on a new, deicated menu/toolbar dedicated to operations (pause queue, retry failed, collapse list, etc.)

Perhaps I can just add the button when I do the rewrite.

**Comment by mrixner** [comment]
Alright, I guess just leave this here until you do that then.

**Comment by mrixner** [comment]
As this was added in #3070, I'm closing this PR.

**Pull request closed without merging**
